### ISSUE TITLE
Hook Circle CI to PR process

### ISSUE THREAD

**Issue by jperata** [bespoken/utterance-gatherer#10]
We need to ensure that the code works as expected, at the moment we are not running tests on PR's.

First, we need to ensure the tests run with our changes.
Then we need to hook Circle CI to utterance gatherer.
Finally, we need to mark the test and coverage passing as required.

**Comment by dmarvp** [comment]
@jperata can we close this one?

**Comment by jperata** [comment]
We have ci now, but still no tests, we could close this one. And create one ticket just for the tests
