### ISSUE TITLE
Comments from internal demo (part 1)

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#17]
On the Common Voice Project
--------------------------------
1. Hide share button
2. Hide back and Talk button
3. After clicking Send there are 2 popups that shouldn't appear, one is for accepting the terms and conditions coming from Common voice and the other one is a "Leaving page" popup 
4. Remove the phrase at the end that says that you contributed to common voice.

**Comment by MKen-li** [comment]
Marked as verified
