### ISSUE TITLE
Update the RDS SSL Certificates

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#19]
### Description
From an Amazon email:

> Hello,
>
>Please act before October 31, 2019 to address an upcoming interruption of your applications using RDS and Aurora database instances.
>
>To protect your communications with RDS database instances, a Certificate Authority (CA) generates time-bound certificates that are checked by your database client software to authenticate any RDS database instance(s) before exchanging information. Following industry best practices, AWS renews the CA and creates new certificates on a routine basis to ensure RDS customer connections are properly protected for years to come. The current CA expires on March 5, 2020, requiring updates to existing RDS database instances with certificates referencing the current CA.
>
>You are receiving this message because you have an Amazon RDS database instance(s) in the US-EAST-1 or US-EAST-2 Region(s). If your applications connect to those instances using the Secure Sockets Layer (SSL) or Transport Layer Security (TLS) protocol please follow the detailed instructions in the link below to complete your update(s). If not completed, your applications will fail to connect to your DB instances using SSL/TLS after March 5, 2020.
>
>We encourage you to test these steps within a development or staging environment before implementing them in your production environments. Beginning today, you can start testing and updating your existing RDS database instances. For detailed instructions, please visit: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html 
>
>Any new RDS instances created after November 1, 2019 will default to using the new certificates. If you wish to temporarily modify new instances manually to use the old (rds-ca-2015) certificates, you can do so using the AWS console or the AWS CLI. Any instances created prior to November 1, 2019 will have the rds-ca-2015 certificates until you update them to the rds-ca-2019 version.
>
>If you have questions or issues, please contact AWS Support at: https://aws.amazon.com/support
>
>Sincerely,
>Amazon Web Services

Please, take a look and follow the instructions detailed above.

**Comment by jricaldi** [comment]
change updated 
![image](https://user-images.githubusercontent.com/2177405/67234547-fcd24600-f40a-11e9-9ed4-db2379b7489c.png)

**Comment by MKen-li** [comment]
Closing ticket,
No QA needed
