### ISSUE TITLE
Comments from Internal Demo - Part 2

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#23]
### What steps, if any, were confusing?
- [x] The last step (submission) was confusing only because my screen wasn't big enough to see the submit button, so I had to scroll.
> We should make sure to put the submit button at the top and at the bottom (considering we will expand from only 5 phrases)

- [x] there was a survey to create an account for something but I kinda skipped it I don't think that is a required step
> Remove as much as we can from Common Voice messaging and extra stuff

- [x] At the end when asked to register in the common voice page, and at the same time having the popup to leave the page.
> Again, remove the registering to common voice part

- [x] Didn't know what I had to do until I saw the UI saying I had to record the text shown on the screen.
> This we can make better when creating the HIT descriptions.

- [x] Once you recorded there was a text at the top that said: "When you're done, click (checkbox icon)", but the actual checkbox was at the bottom.
> This kind of things should go at the top and the bottom

- [x] Accepting terms and conditions at the end, as well as the "leave the page" question
> Terms and conditions can be removed 

### Usability issues
- [x] After each step, 3 icons appear on the right side. The rightmost icon did not have mouseover text. It was also odd that the other icons disappear when you hit the play to review.
> Need to check on this one

- [x] Add instructions: record in a silent room, use an external mic, etc. Anything that can ensure we get better quality. 
> We can add messaging like this on the recording page

**Comment by dmarvp** [comment]
Yeah, I agree. We need a standard HIT description and a UI redesign where we can include this.

**Comment by MKen-li** [comment]
Marked as verified
