### ISSUE TITLE
Retrieve list of utterances from an S3 file

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#4]
### Description
Currently, the utterances that a user should record come from a Mozilla endpoint. We want to change it so that we can read utterances from an S3 txt file in where each line represents a new utterance that should be shown on the screen.

For this to work, we need to assign an id to each S3 file and the page that shows the utterances should receive an id parameter, which it'll use to load the utterances from that file.

**Comment by jricaldi** [comment]
- Upload your utterance.txt in the bucket voice-web-bespoken-sentences following the next path `:contractor/:locale/utterance.txt`
- Using postman to import this file `{{VOICE_WEB_DOMAIN}}/api/v1/import/sentences/:contractor/:locale`
- the result should be `"status": "importing SUCCESS"`
- check the sentence in mysql

**Comment by MKen-li** [comment]
Marked as verified
