### ISSUE TITLE
Create mechanical turk projects and HITs from the AWS SDK 

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#5]
### Summary
Using the AWS SDK we should create a console script that will let us create Projects and HITs on Mechanical Turk on demand.

The script should take the following params from an ENV file:
- aws_access_key_id
- aws_secret_access_key
- prod (true|false): the default should be false. Depending on the value, the endpoint to use should be:
  - 'https://mturk-requester-sandbox.us-east-1.amazonaws.com'
  - 'https://mturk-requester.us-east-1.amazonaws.com'
- AssignmentDurationInSeconds
- Description
- LifetimeInSeconds
- Reward
- Title
- Keywords
- MaxAssignments
- ExternalQuestionURL

With those values, we'll create a HIT with an external question like this one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ExternalQuestion xmlns="[the ExternalQuestion schema URL]">
  <ExternalURL> ExternalQuestionURL </ExternalURL>
  <FrameHeight>0</FrameHeight>
</ExternalQuestion>
```

Additionally, we need to figure out how to create a project where this HIT is going to be contained. This is important for us because that way we can see it and manage it from the MTurk Requester Dashboard.

**Comment by MKen-li** [comment]
Marked as verified
