### ISSUE TITLE
Modify the Recording page to get data from and send data to Mechanical Turk

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#6]
### Summary
The speak page of our common voice project (https://commonvoice.bespoken.tools/en/speak) has to be modified so that it is prepared to receive the following parameters:
- assignmentId
- hitId
- workerId
- turkSubmitTo

After recording 5 audio clips, clicking on submit should post the result data back to Amazon Mechanical Turk as explained here: https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html#ApiReference_ExternalQuestionArticle-the-external-form

Additionally, the first 3 parameters should be saved in our database as well along with the submitted audios.

**Comment by MKen-li** [comment]
Marked as verified
