### ISSUE TITLE
Modify the Listen Page to retrieve specific audios

### ISSUE THREAD

**Issue by dmarvp** [bespoken/utterance-gatherer#7]
### Summary
Using the data that was saved on #6 , we should be able to retrieve recordings associated with a specific /hit/worker/assignment. So, by adding those values as query parameters we'll bring those audios for review.

### Notes
This will let us manually review the audios before accepting the assignments sent in #6 to Mechanical Turk.

**Comment by jricaldi** [comment]
the way to get the audios from the worker is just `{{VOICE_WEB_DOMAIN}}/es/listen?contractor=everis&assignmentId=3R2UR8A0IBVSMRD04CIQVRYG6SKXOE`

* it's important to mention the `contractor` field help to increase the query selecting.

**Comment by jricaldi** [comment]
the way to get the audios from the worker is just `{{VOICE_WEB_DOMAIN}}/{{locale}}/listen?contractor={{contractor}}&assignmentId={{assignmentId}}`

* it's important to mention the `contractor` field help to increase the query selecting.

**Comment by MKen-li** [comment]
Moving ticket back to dev,
We need to be able to listen to the audio files

**Comment by jricaldi** [comment]
The issue about "listen to mp3 files" was related to the equalizer sound chrome plugin. If you have same problem, please disable it or use private mode or another browser.

**Comment by MKen-li** [comment]
Marked as verified
